server:
  port: 8080
spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://www.daoyang.design:3306/user_center?characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: yedeyang
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 7dba8a31-94bf-444f-81ef-7d36ff38f630
        cluster-name: NJ
        metadata:
          version: v1
