spring:
  application:
    name: usercenter
  datasource:
    url: jdbc:mysql://www.daoyang.design:3306/user_center?characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: yedeyang
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8

  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
server:
  port: 8080
