spring:
  datasource:
    url: jdbc:mysql://www.daoyang.design/content_center?characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: yedeyang
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
server:
  port: 8081